server:
  port: 8088
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/hospital?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 141422
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    check-template-location: true
    template-loader-path: classpath:/templates
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    request-context-attribute: request
  mvc:
    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.hospital.entity
  http:
    multipart:
      maxFileSize: 500Mb
      maxRequestSize: 500Mb
filepath:
  appointpdf: ./
  seekpdfpath: ./